---
job: extension
config:
  name: flux2_klein_9b_print_extract_c1_weighted
  process:
  - type: diffusion_trainer
    training_folder: /root/ai-toolkit/output
    sqlite_db_path: ./aitk_db.db
    device: cuda
    trigger_word: null
    network:
      type: lora
      linear: 32
      linear_alpha: 32
    save:
      dtype: bf16
      save_every: 500
      max_step_saves_to_keep: 10
      save_format: diffusers
      push_to_hub: false
    datasets:
    - folder_path: /root/ai-toolkit/datasets/V16/background_control-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/background_control-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/background_control_key_color-2/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/background_control_key_color-2/control
      num_repeats: 2
    - folder_path: /root/ai-toolkit/datasets/V16/material-2/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/material-2/control
      num_repeats: 2
    - folder_path: /root/ai-toolkit/datasets/V16/color_adjustment-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/color_adjustment-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/vintage_style-2/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/vintage_style-2/control
      num_repeats: 2
    - folder_path: /root/ai-toolkit/datasets/V16/furry_animals-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/furry_animals-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/blurry_reconstruction-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/blurry_reconstruction-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/difficult_reconstruction-2/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/difficult_reconstruction-2/control
      num_repeats: 2
    - folder_path: /root/ai-toolkit/datasets/V16/general_reconstruction-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/general_reconstruction-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/perspective_correction-2/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/perspective_correction-2/control
      num_repeats: 2
    - folder_path: /root/ai-toolkit/datasets/V16/people-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/people-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/physical_objects-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/physical_objects-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/color_consistency_control-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/color_consistency_control-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/text_reconstruction-3/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/text_reconstruction-3/control
      num_repeats: 3
    - folder_path: /root/ai-toolkit/datasets/V16/fine_details-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/fine_details-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/line_detail-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/line_detail-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/small_graphics-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/small_graphics-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/oil_painting-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/oil_painting-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/occlusion_reconstruction-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/occlusion_reconstruction-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/wrinkle_flattening-3/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/wrinkle_flattening-3/control
      num_repeats: 3
    - folder_path: /root/ai-toolkit/datasets/V16/pearl-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/pearl-1/control
      num_repeats: 1
    - folder_path: /root/ai-toolkit/datasets/V16/realistic_flora-1/target
      default_caption: "reconstruct the original garment graphic print, preserve exact colors, proportions and original texture, output a flat printable graphic on a clean solid background"
      caption_ext: txt
      network_weight: 1
      resolution: [512, 768, 1024, 1280, 1328, 1536]
      full_size_control_images: true
      control_path_1: /root/ai-toolkit/datasets/V16/realistic_flora-1/control
      num_repeats: 1
    train:
      batch_size: 1
      steps: 3200
      gradient_accumulation: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      timestep_type: weighted
      content_or_style: balanced
      optimizer_params:
        weight_decay: 0.0001
      lr: 6.0e-05
      dtype: bf16
      loss_type: wavelet
    model:
      name_or_path: black-forest-labs/FLUX.2-klein-base-9B
      quantize: true
      qtype: qfloat8
      quantize_te: true
      qtype_te: qfloat8
      arch: flux2_klein_9b
      low_vram: true
      model_kwargs:
        match_target_res: false
    sample:
      sampler: flowmatch
      sample_every: 250
      width: 1024
      height: 1024
      samples: []
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 30
      num_frames: 1
      fps: 1
    logging:
      log_every: 1
      use_ui_logger: true
meta:
  name: flux2_klein_9b_print_extract_c1_weighted
  version: 'C1'
